### ISSUE TITLE
MATT: Give us file so we can normalize metrics

### ISSUE THREAD

**Issue by amitrajesh** [hrc2da/experiments-workbench#2]

**Comment by mattvlaw** [comment]
Data file I've been using for normalization is here:
https://cornell.box.com/s/3lclawi4ymo5p68c048vqix3ihtfe3t3


It contains a list of means and a list of standard deviations for each weight feature (there are 5 and it is in order ['population', 'pvi','compactness','projected_votes','race']).

Please pass this as a yaml param (the file) so that we can change it and rerun if necessary.

Some sample code to use it:

`with open(standardization_f,'rb') as sfile:
    standard_m, standard_std = pkl.load(sfile)
def metric_standardize(data, m, std):
    data = np.array(data)
    return (data - m)/std`

We should also discuss a strategy for maintaining data files without pushing to the repo. This one is small, but others may not be.
